README.md

Atualizado o README, adicionando passos para configurar o projeto para executar em ambiente de desenvolvimento.

Update README adding step to run in local development.

---

.github/pull_request_template.md
pom.xml
src/main/java/br/com/itsmemario/ecordel/file/FtpConfig.java
src/main/java/br/com/itsmemario/ecordel/file/FtpFileManager.java
src/main/java/br/com/itsmemario/ecordel/file/LocalFileManager.java
src/main/java/br/com/itsmemario/ecordel/xilogravura/XilogravuraService.java
src/main/resources/application-local.yml
src/main/resources/application.yml
src/test/java/br/com/itsmemario/ecordel/file/FtpClientsTest.java
src/test/java/br/com/itsmemario/ecordel/xilogravura/XilogravuraServiceTest.java
src/test/resources/application.yml

Add ftp client to handle images upload

Ftp client

---

.github/workflows/build.yml
pom.xml

what was changed
- pom.xml with sonar properties
- github action to use/push code to sonar cloud

Configure sonar cloud

---

pom.xml

Add jacoco plugin to generate test coverage report on sonar 
- pom.xml

Add jacoco-plugin

---

.gitignore
docker-compose.yml

moving volume datadir outside target and adding gitignore for new folder

moving volume datadir outside target

---

.github/workflows/build.yml
.github/workflows/new-pr.yml
pom.xml

Add plugin para verificar vulnerabilidades nas dependências.
Incluí também uma notificação para o discord em caso do build falhar.
Alterações
- pom.xml
- build action

Add dependency check plugin

---

pom.xml
src/main/java/br/com/itsmemario/ecordel/author/Author.java
src/main/resources/db/migration/V1.2__author-type-changed-field.sql
src/test/java/br/com/itsmemario/ecordel/author/AuthorDtoTest.java

- mapping name to the authorDTO
- mapping name on Author.of
- changing type on db

changing db type, adding unit test and changint class dto

---

src/main/java/br/com/itsmemario/ecordel/EcordelApplication.java
src/main/java/br/com/itsmemario/ecordel/security/AuthenticationService.java
src/main/java/br/com/itsmemario/ecordel/security/jwt/JwtToken.java
src/main/java/br/com/itsmemario/ecordel/security/jwt/JwtTokenRepository.java
src/main/java/br/com/itsmemario/ecordel/security/jwt/JwtTokenService.java
src/main/resources/application-local.yml
src/main/resources/db/migration/V1.1__create-jwt-token-table.sql
src/test/java/br/com/itsmemario/ecordel/security/jwt/JwtTokenTest.java

moving jwt token to database
- creating jwt token table
- injecting jwt token in AuthenticationService class

moving JwtToken to database

---

README.md
pom.xml
src/main/java/br/com/itsmemario/ecordel/author/Author.java
src/main/java/br/com/itsmemario/ecordel/author/AuthorController.java
src/main/java/br/com/itsmemario/ecordel/author/AuthorDto.java
src/main/java/br/com/itsmemario/ecordel/cordel/CustomCordelRepositoryImpl.java
src/main/resources/db/migration/V1.2__author-type-changed-field.sql
src/test/java/br/com/itsmemario/ecordel/AbstractIntegrationTest.java
src/test/java/br/com/itsmemario/ecordel/EcordelApplicationTests.java
src/test/java/br/com/itsmemario/ecordel/author/AuthorControllerTest.java
src/test/java/br/com/itsmemario/ecordel/author/AuthorDtoTest.java
src/test/java/br/com/itsmemario/ecordel/author/AuthorRepositoryTest.java
src/test/java/br/com/itsmemario/ecordel/cordel/CordelControllerTest.java
src/test/java/br/com/itsmemario/ecordel/cordel/CordelRepositoryTest.java

- Muda tipo de dado to campo `about` para permitir longos textos.
- Fix security sonar issues

Author about attribute

---

.gitignore
openapi.yaml
pom.xml
src/main/java/br/com/itsmemario/ecordel/author/AuthorController.java

Fix Location header

---

.github/workflows/build.yml
Dockerfile
README.md
pom.xml
src/main/java/br/com/itsmemario/ecordel/security/SecurityConfig.java
src/main/java/br/com/itsmemario/ecordel/security/TokenDto.java
src/main/resources/application.yml
src/test/java/br/com/itsmemario/ecordel/AbstractIntegrationTest.java
src/test/java/br/com/itsmemario/ecordel/EcordelApplicationTests.java
src/test/java/br/com/itsmemario/ecordel/author/AuthorControllerTest.java
src/test/java/br/com/itsmemario/ecordel/cordel/CordelControllerTest.java
src/test/java/br/com/itsmemario/ecordel/security/AuthenticationControllerTest.java
src/test/resources/db/data/add-admin-user.sql
src/test/resources/db/data/clean-user-authorities.sql
src/test/resources/db/data/user.sql

adiciona check de permissão de admin para `POST /authors`

FIX - permissão para o endpoint post /authors

---

.github/workflows/build.yml
README.md
dependency-check-suppressions.xml
pom.xml

Add file to suppress false positives during dependency check scan

Suprress tomcat vulnerability disabled by spring - CVE-2022-23181

---

.github/workflows/build.yml

This PR add an environment to eb deploy step

add environment to eb deploy step

---

.github/workflows/build.yml
.github/workflows/checks.yml
README.md
dependency-check-suppressions.xml
pom.xml
src/main/java/br/com/itsmemario/ecordel/author/AuthorController.java
src/main/java/br/com/itsmemario/ecordel/author/AuthorService.java
src/main/java/br/com/itsmemario/ecordel/cordel/CordelRepository.java
src/main/java/br/com/itsmemario/ecordel/cordel/CordelSummary.java
src/main/java/br/com/itsmemario/ecordel/security/SecurityConfig.java
src/main/resources/application-local.yml
src/test/java/br/com/itsmemario/ecordel/AbstractIntegrationTest.java
src/test/java/br/com/itsmemario/ecordel/author/AuthorControllerTest.java

- Cria endpoints GET e PUT
- Resolve dependency check issues

Edit authors

---

dependency-check-suppressions.xml

- dependency-check-suppressions.xml

Suppress some snakeyaml vulnerabilities

---

.github/workflows/build.yml
README.md
pom.xml
src/main/java/br/com/itsmemario/ecordel/EcordelApplication.java
src/main/java/br/com/itsmemario/ecordel/author/Author.java
src/main/java/br/com/itsmemario/ecordel/author/AuthorController.java
src/main/java/br/com/itsmemario/ecordel/author/AuthorDto.java
src/main/java/br/com/itsmemario/ecordel/cordel/Cordel.java
src/main/java/br/com/itsmemario/ecordel/cordel/CordelController.java
src/main/java/br/com/itsmemario/ecordel/cordel/CordelDto.java
src/main/java/br/com/itsmemario/ecordel/file/LocalFileManager.java
src/main/java/br/com/itsmemario/ecordel/security/AuthenticationController.java
src/main/java/br/com/itsmemario/ecordel/security/CordelAuthority.java
src/main/java/br/com/itsmemario/ecordel/security/CordelUser.java
src/main/java/br/com/itsmemario/ecordel/security/SecurityConfig.java
src/main/java/br/com/itsmemario/ecordel/security/TokenAuthenticationFilter.java
src/main/java/br/com/itsmemario/ecordel/security/jwt/JwtToken.java
src/main/resources/application-local.yml
src/test/java/br/com/itsmemario/ecordel/author/AuthorRepositoryTest.java
src/test/java/br/com/itsmemario/ecordel/cordel/CordelControllerTest.java
src/test/java/br/com/itsmemario/ecordel/security/AuthenticationControllerTest.java
system.properties

Upgrade Spring boot to version 3 and JDK 17
- Spring boot 3
- Java 17

upgrade spring to 3 and jdk to 17

---

.github/workflows/build.yml
dependency-check-suppressions.xml
pom.xml

Upgrade spring boot and suppress false positive vulnerability

Upgrade Spring Boot

---

openapi.yaml
pom.xml
src/main/java/br/com/itsmemario/ecordel/author/AuthorController.java
src/main/java/br/com/itsmemario/ecordel/author/AuthorNotFoundException.java
src/main/java/br/com/itsmemario/ecordel/cordel/CordelController.java
src/main/java/br/com/itsmemario/ecordel/cordel/CordelRepository.java
src/main/java/br/com/itsmemario/ecordel/cordel/CordelService.java
src/main/java/br/com/itsmemario/ecordel/cordel/CordelSummaryRequest.java
src/main/resources/application-local.yml
src/test/java/br/com/itsmemario/ecordel/cordel/CordelRepositoryTest.java
src/test/java/br/com/itsmemario/ecordel/cordel/CordelServiceTest.java

Add cordel filter by author
- Added AuthorNotFoundException
- Changed queries in CordelRepository to add filter by author
- Create CordelSummaryRequest to wrap request params
- Improve tests

Add cordel filter by author

---

pom.xml

short description
fixed vulnerabilities.
- upgrade version spring-boot to 3.1.7.
- upgrade version dependency-check-maven to 8.4.3.
- upgrade version testcontainers-postregesql to 1.19.3.

Fixed Vulnerabilities

---

pom.xml

Upgrade versions of dependencies report on dependency check.
- upgrade spring-boot-parent to 3.1.10 and dependency-check to 9.1.0.
- upgrade dependencies with reported on dependency-check report.
- upgrade version to 1.5.1.

Resolve CVES Dependency Check

---

.github/workflows/build.yml

short description
- update build.yml
- upgrade version of actions checkout, cache, setup-java and upload-artifacts.

Upgrade versions of actions to fix failed build
